### ISSUE TITLE
Feature 1: User can access artist and gallery view

### ISSUE THREAD

**Issue by tinachia** [tinachia/ajax-project#1]
## 📐 Plan

> ##### Users can access different  views on the website and have the ability to go back to the homepage view

## 🖼️ Wireframes

> ##### 

![image](https://user-images.githubusercontent.com/110127607/202772965-2f6bfc1a-f4e4-4e00-8add-351d9558854d.png)

![image](https://user-images.githubusercontent.com/110127607/202773017-fe658c59-eeed-492d-962a-a00538a558dd.png)
![image](https://user-images.githubusercontent.com/110127607/202773196-6d833da2-8c6f-4ed2-b255-bc51af47f365.png)

## ✅ Task List

- [x]  Add a div[data-view="home-page"] to the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Add a div[data-view="Artist-Page"] and div[data-view="Gallery-Page"]
- [x] linked button in order to access all view pages
- [x] Listen for 'click' events to view swap from different view pages
Clean Up
 - [x] Confirm that there are no errors in the console while using the application.
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x]  Test all functionality again in a private browsing session.
 - [x] Fix all errors.
