### ISSUE TITLE
Feature 2: User can access artist view page

### ISSUE THREAD

**Issue by tinachia** [tinachia/ajax-project#2]
## 📐 Plan

> #####Users can search access artist view page with specific artists listed

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/110127607/202777420-30148a85-2a8e-4d4c-9915-f2d41b208c9b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Hide other pages when clicked on artist button on nav bar
- [x] Hide other pages when clicked on artist button under artist photo
- [x] display artist information: name, picture, bio
- Clean Up
 - [x] Confirm that there are no errors in the console while using the application.
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x]  Test all functionality again in a private browsing session.
 - [x] Fix all errors.
