### ISSUE TITLE
Feature 4: User can like or unlike artwork

### ISSUE THREAD

**Issue by tinachia** [tinachia/ajax-project#3]
## 📐 Plan

> ##### Users can like artist work to have it added(or  remove) from their favorite list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/110127607/202783860-7bcc8473-f9f7-41e6-8cc8-d10b07559892.png)

![image](https://user-images.githubusercontent.com/110127607/202783885-e2c728b1-56ed-4368-a884-b3e19d371014.png)

## ✅ Task List

- [ ]  Have artwork include a heart icon
- [ ] Listen for clicks and add artwork to favorite page
- [ ] In favorite page include the broken heart icon
- [ ] Listen for clicks and remove artwork from favorite page
Clean Up
 - [ ] Confirm that there are no errors in the console while using the application.
 - [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [ ]  Test all functionality again in a private browsing session.
 - [ ] Fix all errors.
