### ISSUE TITLE
Feature 5: User can access their saved art work page

### ISSUE THREAD

**Issue by tinachia** [tinachia/ajax-project#4]
## 📐 Plan

> ##### Users can access different  views on the website and have the ability to go back to the homepage view

## 🖼️ Wireframes

> ##### 

![image](https://user-images.githubusercontent.com/110127607/202773196-6d833da2-8c6f-4ed2-b255-bc51af47f365.png)

![image](https://user-images.githubusercontent.com/110127607/202773233-479a67ad-49f0-4af7-a18d-d54f655315b5.png)

## ✅ Task List

- [ ]  Add a div[data-view="Artist-Page"]to the HTML.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] linked button in order to access view swapping
- [ ] Listen for 'click' events to view swap from different view pages
Clean Up
 - [ ] Confirm that there are no errors in the console while using the application.
 - [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [ ]  Test all functionality again in a private browsing session.
 - [ ] Fix all errors.
