### ISSUE TITLE
Feature 3: User can search up artist's work

### ISSUE THREAD

**Issue by tinachia** [tinachia/ajax-project#7]
## 📐 Plan

> ##### Users can search up available artist's work on artwork page. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/110127607/202783860-7bcc8473-f9f7-41e6-8cc8-d10b07559892.png)

![image](https://user-images.githubusercontent.com/110127607/202783885-e2c728b1-56ed-4368-a884-b3e19d371014.png)

## ✅ Task List

- [x]  search bar to type in artist name
- [x] use public api to retrieve art work specific artist
- [x] append artwork on page
Clean Up
 - [x] Confirm that there are no errors in the console while using the application.
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x]  Test all functionality again in a private browsing session.
 - [x] Fix all errors.
